export const workExperience = [
  {
    id: 1,
    company: 'FUTURENOSTICS',
    location: 'E11, Islamabad, Pakistan',
    position: 'SOFTWARE ENGINEER',
    startDate: '31/10/2024',
    endDate: 'CURRENT',
    responsibilities: [
      'Contributed across the full AEDI platform—React frontends, NestJS APIs, FastAPI AI services, GIS integrations, billing, and cloud deployments for a multi-tenant municipal planning SaaS focused on automated zoning and land-development assessments.',
      'Developed municipality-specific GIS and AI workflows using ArcGIS, PostGIS, FastAPI, LangChain, OpenAI, and RAG pipelines for zoning bylaws, parcel data, permitted-use analysis, dimensional checks, and planning constraints across Canadian municipalities.',
      'Built and maintained scalable backend and cloud infrastructure with NestJS, PostgreSQL, Redis, Docker, AWS ECS, and GCP; contributed to Stripe billing, HIPAA-compliant systems, RBAC, automation services, and production debugging across distributed systems.',
      'Built a Medicaid compliance platform on GCP using Cloud Run, Artifact Registry, and Docker-based deployments.',
      'Developed a SaaS Sales Management System for e-commerce businesses to manage sales, inventory, and order workflows.',
      'Implemented RBAC with granular roles and permissions; created a HIPAA-compliant dynamic form builder for the Case Management Hub.',
      'Automated operational workflows by integrating Monday.com with Google Sheets; collaborated in Agile environments using Jira.',
    ],
  },
  {
    id: 2,
    company: 'ARGONTEQ',
    location: 'Model Town, Lahore',
    position: 'BACKEND DEVELOPER',
    startDate: '31/05/2023',
    endDate: '30/11/2024',
    responsibilities: [
      'Developed backend services for an educational CRM—student profiles, enrollments, authentication workflows, and academic progress tracking for admins and parents.',
      'Built secure authentication and user management with RBAC to support different access levels across platform users.',
      'Developed Willo Box, an AI-powered document query platform using OpenAI APIs and LangChain for PDF uploads and context-aware semantic search.',
      'Contributed to a crypto exchange backend with Node.js and MongoDB for user management, transactions, and secure data operations.',
      'Built backend systems for a gaming platform with game management, tournament organization, and admin-controlled content publishing.',
      'Integrated Google Reviews into a restaurant tipping platform; developed pharmacy marketplace workflows for registrations, listings, and transactions.',
      'Collaborated with frontend, QA, and project managers in Agile environments to deliver scalable APIs and integrations.',
    ],
  },
]
