export const workExperience = [
  {
    id: 1,
    company: 'FUTURENOSTICS',
    location: 'E11, Islamabad, Pakistan',
    position: 'SOFTWARE ENGINEER',
    startDate: '31/10/2024',
    endDate: 'CURRENT',
    responsibilities: [
      'Design and develop scalable backend services and modern frontend features for AEDI, a multi-tenant municipal planning SaaS used by Canadian municipalities for zoning and land development assessments.',
      'Build HIPAA-compliant healthcare solutions—dynamic form builders, workflow automation, secure case management, and enterprise backend services.',
      'Engineer cloud-native applications with NestJS, React.js, FastAPI, PostgreSQL, Redis, Docker, AWS ECS, and GCP for scalability and high availability.',
      'Design secure authentication, authorization, and RBAC across enterprise SaaS applications; integrate Stripe, GIS platforms, and external APIs.',
      'Developed the Sales Management System SaaS for products, inventory, customers, orders, and sales operations.',
      'Developed Sidekick, an Agentic AI assistant with Python, LangChain, and LangGraph for multi-step planning, tool calling, and human-in-the-loop workflows.',
      'Built Autonomous Trading Floor, a multi-agent AI platform with Python, OpenAI Agents SDK, and MCP for financial research and autonomous agent orchestration.',
    ],
  },
  {
    id: 2,
    company: 'ARGONTEQ',
    location: 'Model Town, Lahore',
    position: 'BACKEND DEVELOPER',
    startDate: '31/05/2023',
    endDate: '30/11/2024',
    responsibilities: [
      'Developed scalable backend services and RESTful APIs with Node.js, NestJS, Express.js, MongoDB, and PostgreSQL for SaaS, fintech, healthcare, gaming, and education platforms.',
      'Built Willo Box, an AI document intelligence platform using OpenAI, LangChain, vector embeddings, and semantic search.',
      'Designed secure authentication, authorization, and RBAC for enterprise applications.',
      'Contributed to a cryptocurrency exchange backend—user management, transaction processing, and secure API integrations.',
      'Built backend services for pharmacy marketplace, restaurant engagement, gaming, and educational CRM platforms.',
      'Integrated Google Reviews, payment gateways, and external APIs; collaborated with frontend, QA, and product in Agile teams.',
    ],
  },
]
