export const workExperience = [
  {
    id: 1,
    company: 'FUTURENOSTICS',
    location: 'E11, Islamabad, Pakistan',
    position: 'SOFTWARE ENGINEER',
    startDate: '30/11/2024',
    endDate: 'CURRENT',
    responsibilities: [
      'Built a Medicaid compliance system on Google Cloud Platform (GCP), using Cloud Run for serverless deployment and Artifact Registry to manage containers securely.',
      'Built a Sales Management System for e-commerce businesses to handle sales, inventory, and orders more easily.',
      'Added Role-Based Access Control (RBAC) with custom roles and permissions to make the system more secure and block unauthorized access.',
      'Worked with cross-functional teams using Agile methods, tracked tasks in Jira, and delivered features on time with high quality.',
      'Used Docker to containerize the app and speed up deployments.',
      'Set up Husky pre-commit hooks to catch code issues early and keep quality high.',
      'Automated workflows by connecting Monday.com with Google Sheets, saving time for the team.',
      'Created a HIPAA-compliant custom form builder for the Case Management Hub so staff members can create, send, and manage forms easily.',
    ],
  },
  {
    id: 2,
    company: 'ARGONTEQ',
    location: 'Model Town, Lahore',
    position: 'BACKEND DEVELOPER',
    startDate: '08/06/2023',
    endDate: '27/12/2024',
    responsibilities: [
      'Developed backend for an educational CRM, managing student profiles, enrolments, and progress tracking.',
      'Built user registration and authentication modules for secure admin and parent access.',
      'Created a document query platform (Willo Box) using OpenAI APIs and LangChain to process PDF uploads and answer context-based questions.',
      'Developed secure backend for a crypto exchange platform, utilising MongoDB for user data and transactions.',
      'Built backend for a gaming platform, allowing users to play games and admins to upload new games, with tournament organisation features.',
      'Contributed to a restaurant tipping platform by integrating Google Reviews to enhance customer and restaurant interactions.',
      'Developed a platform for pharmacies to buy and sell medications, managing transactions and pharmacy registrations.',
    ],
  },
]
